-- 코드를 입력하세요
SELECT  WRITER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) 전체주소, CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) 전화번호

  FROM  USED_GOODS_BOARD A, USED_GOODS_USER B

 WHERE  WRITER_ID = USER_ID
 
 GROUP
    BY  WRITER_ID

HAVING  COUNT(*) >= 3

 ORDER
    BY  WRITER_ID DESC