SELECT QUARTER, COUNT(*) ECOLI_COUNT
FROM  # QUARTER
    (SELECT  CASE 
            WHEN CAST(SUBSTR(DIFFERENTIATION_DATE, 6, 2) AS SIGNED) <= 3 THEN '1Q'
            WHEN CAST(SUBSTR(DIFFERENTIATION_DATE, 6, 2) AS SIGNED) <= 6 THEN '2Q'
            WHEN CAST(SUBSTR(DIFFERENTIATION_DATE, 6, 2) AS SIGNED) <= 9 THEN '3Q'
            WHEN CAST(SUBSTR(DIFFERENTIATION_DATE, 6, 2) AS SIGNED) <= 12 THEN '4Q'
            END AS QUARTER
      FROM  ECOLI_DATA) A
    
 GROUP
    BY  QUARTER

 ORDER
    BY  QUARTER