SELECT  CONCAT('/home/grep/src/', A.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH

  FROM  USED_GOODS_FILE A
  
 WHERE  A.BOARD_ID = (SELECT B.BOARD_ID FROM USED_GOODS_BOARD B ORDER BY B.VIEWS DESC LIMIT 1) 
 
 ORDER
    BY  FILE_ID DESC
